# Generated by Django 4.2.7 on 2024-08-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='for_contato',
            field=models.CharField(default=-4920, max_length=255),
            preserve_default=False,
        ),
    ]
