# Generated by Django 4.2.7 on 2024-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_fornecedor_for_contato'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='pro_codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
